# Generated by Django 5.1.2 on 2025-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[(1, 'Telefon'), (2, 'Tartozék')], default=1),
        ),
    ]
