# Generated by Django 5.1.2 on 2025-09-23 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0002_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='image_path',
            field=models.CharField(default='default.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
