# Generated by Django 5.1.2 on 2025-09-23 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0003_products_available_products_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
