# Generated by Django 5.2 on 2025-09-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneshop", "0004_alter_products_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[("1", "Telefon"), ("2", "Tartozék")], default="1"
            ),
        ),
        migrations.CreateModel(
            name="Specs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CPU_speed", models.CharField(max_length=255)),
                ("CPU_type", models.CharField(max_length=255)),
                ("display_size", models.CharField(max_length=255)),
                ("resolution", models.CharField(max_length=255)),
                ("display_technology", models.CharField(max_length=255)),
                ("max_refresh_rate", models.CharField(max_length=255)),
                ("Spen", models.BooleanField(default=False)),
                ("camera", models.CharField(max_length=255)),
                ("memory", models.CharField(max_length=255)),
                ("storage", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("charge", models.CharField(max_length=255)),
                ("sensors", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=255)),
                ("weight", models.CharField(max_length=255)),
                ("battery", models.IntegerField()),
                ("release_date", models.DateField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="phoneshop.products",
                    ),
                ),
            ],
        ),
    ]
