# Generated by Django 5.1.2 on 2025-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0006_alter_specs_memory_alter_specs_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('1', 'Westend'), ('2', 'Árkád'), ('3', 'Pólus')], default='1')),
            ],
        ),
    ]
