# Generated by Django 5.1.2 on 2025-09-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0007_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(choices=[('1', 'Westend'), ('2', 'Árkád'), ('3', 'Pólus')], default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('position', models.CharField(choices=[('uzletvezeto', 'Üzletvezető'), ('ertekesito', 'Értékesítő'), ('promoter', 'Promoter')], default='uzletvezeto')),
                ('admin', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='phoneshop.shops')),
            ],
        ),
    ]
