# Generated by Django 5.1.2 on 2025-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0008_alter_shops_location_alter_shops_name_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phoneshop.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phoneshop.shops')),
            ],
        ),
    ]
