# Generated by Django 5.1.2 on 2025-09-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0009_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='phoneshop.workers')),
            ],
        ),
    ]
