# Generated by Django 5.1.2 on 2025-09-23 16:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0010_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('num_items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='phoneshop.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='phoneshop.shops')),
            ],
        ),
    ]
