# Generated by Django 5.1.2 on 2025-09-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0011_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('selling_time', models.DateTimeField()),
                ('tax_number', models.IntegerField(max_length=10)),
                ('zip_code', models.IntegerField(max_length=4)),
                ('address', models.CharField(max_length=255)),
                ('costumer_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='phoneshop.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='phoneshop.shops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='phoneshop.users')),
            ],
        ),
    ]
