# Generated by Django 5.1.2 on 2025-09-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0012_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='phoneshop.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='phoneshop.shops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='phoneshop.users')),
            ],
        ),
    ]
