# Generated by Django 5.1.2 on 2025-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0013_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('telefon', 'Telefon'), ('tartozek', 'Tartozék')], default='telefon'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(choices=[('westend', 'Westend'), ('arkad', 'Árkád'), ('polus', 'Pólus')], default='westend'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(choices=[('uzletvezeto', 'Üzletvezető'), ('ertekesito', 'Értékesítő'), ('promoter', 'Promóter')], default='uzletvezeto'),
        ),
    ]
