# Generated by Django 5.1.2 on 2025-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0014_alter_products_category_alter_shops_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('feldolgozás_alatt', 'Feldolgozás alatt'), ('kiszállítva', 'Kiszállítva'), ('törölve', 'Törölve')], default='feldolgozás alatt'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(choices=[('westend', 'Westend'), ('árkád', 'Árkád'), ('pólus', 'Pólus')], default='westend'),
        ),
    ]
