# Generated by Django 5.2 on 2025-09-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneshop", "0015_alter_orders_status_alter_shops_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="password",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AddField(
            model_name="users",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phoneshop_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="tax_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="sales",
            name="zip_code",
            field=models.CharField(max_length=4),
        ),
    ]
