# Generated by Django 5.1.2 on 2025-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0015_alter_orders_status_alter_shops_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Telefon', 'Telefon'), ('Tartozék', 'Tartozék')], default='Telefon'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='zip_code',
            field=models.CharField(max_length=4),
        ),
    ]
