# Generated by Django 5.2 on 2025-09-24 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneshop", "0016_remove_users_password_remove_users_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phoneshop_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
