# Generated by Django 5.1.2 on 2025-09-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0016_alter_products_category_alter_sales_tax_number_and_more'),
        ('phoneshop', '0017_alter_users_user'),
    ]

    operations = [
    ]
