# Generated by Django 5.1.2 on 2025-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0018_merge_20250925_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
