# Generated by Django 5.2 on 2025-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneshop", "0019_alter_orders_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="storage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
