# Generated by Django 5.1.2 on 2025-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0020_alter_cart_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prices',
        ),
        migrations.AlterField(
            model_name='sales',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
